### ISSUE TITLE
Fatal error when selecting same currencies

### ISSUE THREAD

**Issue by brianoh** [chinotapales/FlutterCurrencyConverter#1]
When selecting the same currencies for conversion I get an error. After selecting USD to AUD, I then wanted to check the reverse ie. AUD to USD, so I changed the USD to AUD first, but then got the following errors:
🏳️ West African CFA Franc: CFRA408.79688606
I/flutter (23480): 🏳️ CFP Franc: ₣74.02689314
I/flutter (23480): 🇿🇦 South African Rand: R10.25332322
I/flutter (23480): 🇿🇲 Zambian Kwacha: ZK8.46426044
E/flutter (23480): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type '_Smi' is not a subtype of type 'double'
E/flutter (23480): #0      new Convertion.fromJson (package:flutter_currency_conversion/model/convertion.dart:25)
E/flutter (23480): #1      Service.getConvertion (package:flutter_currency_conversion/data/service.dart:55)
E/flutter (23480): <asynchronous suspension>
E/flutter (23480): #2      _MainPageState._getConvertion (package:flutter_currency_conversion/main.dart:188)
E/flutter (23480): <asynchronous suspension>
E/flutter (23480): #3      _MainPageState._getRates.<anonymous closure> (package:flutter_currency_conversion/main.dart:153)

To get the program to function after that, I have to uninstall and reinstall it.

**Comment by chinotapales** [comment]
Hi @brianoh, Aplogies for the delay. It is now fixed with the latest commit 36d742229303477cd01debdfd80696f5bb59cc2a. Thanks for raising that concern :)
